In [ ]:
import pandas as pd

# 네이버
naver_pul_meta = pd.read_csv('네이버_풀무원_메타.csv') # 풀무원 메타
# naver_pul_review = pd.read_csv() # 풀무원 리뷰
naver_bibi_meta = pd.read_csv('네이버_비비고_메타.csv') # 비비고 메타
# naver_bibi_review = pd.read_csv() # 비비고 리뷰
naver_oto_meta = pd.read_csv('네이버_오뚜기_메타.csv') # 오뚜기 메타
# naver_oto_review = pd.read_csv() # 오뚜기 리뷰

# 쿠팡
coupang_pul_meta = pd.read_csv('쿠팡_풀무원_메타.csv') # 풀무원 메타
coupang_pul_review = pd.read_csv('쿠팡_풀무원_리뷰.csv') # 풀무원 리뷰
coupang_bibi_meta = pd.read_csv('쿠팡_비비고_메타.csv') # 비비고 메타
coupang_bibi_review = pd.read_csv('쿠팡_비비고_리뷰.csv') # 비비고 리뷰
coupang_oto_meta = pd.read_csv('쿠팡_오뚜기_메타.csv') # 오뚜기 메타
coupang_oto_review = pd.read_csv('쿠팡_오뚜기_리뷰.csv') # 오뚜기 리뷰

# 자사몰
own_pul_meta = pd.read_csv('자사몰_풀무원_메타.csv') # 풀무원 메타
own_pul_review = pd.read_csv('자사몰_풀무원_리뷰.csv') # 풀무원 리뷰
own_bibi_meta = pd.read_csv('자사몰_비비고_메타.csv') # 비비고 메타
own_bibi_review = pd.read_csv('자사몰_비비고_리뷰.csv') # 비비고 리뷰
own_oto_meta = pd.read_csv('자사몰_오뚜기_메타.csv') # 오뚜기 메타
own_oto_review = pd.read_csv('자사몰_오뚜기_리뷰.csv') # 오뚜기 리뷰

# 메타데이터 기본 데이터셋
브랜드1 | 브랜드2 | 판매처 | 순위 | 상품ID | 상품명 | 평균 별점 | 리뷰 수 | 정가 | 할인가 | 할인율 | 만두상세내용 | 대체지표 | 배송

## 자사몰
### 풀무원
- 순위 열 생성
- 열 이름 수정: 배송 종류 -> 배송

### 비비고
- 순위 열 생성
- 리뷰 평점 열 삭제
- 열 이름 수정: 대체지표1 -> 대체지표
- 열 이름 수정: 배송종류 -> 배송
- Unnamed: 13 열 삭제
- url 삭제

### 오뚜기
- 열 이름 수정: 브랜드 -> 브랜드1
- 열 이름 수정: 브랜드라인 -> 브랜드2
- 판매처 열 생성
- 순위 열 생성
- 열 이름 수정: 별점 -> 리뷰 평점
- 할인율 열 생성 + 값 추가
- 열 이름 수정: 배송비 -> 배송
- url 열 삭제

## 네이버
### 풀무원, 비비고, 오뚜기
- Unnamed: 0 열 삭제
- 순위 열 생성
- 열 이름 변경: 대체지표1(배지) -> 대체지표
- 열 이름 변경: 배송종류 -> 배송
- url 열 제거

In [ ]:
# 풀무원메타 DF 새로 만들어서 'own_pul_meta' 복사
풀무원메타 = own_pul_meta.copy()
풀무원메타.head(5)

,브랜드1,브랜드2,판매처,상품ID,상품명,리뷰수,정가,할인가,할인율,만두 상세내용,대체지표,배송종류
0,풀무원,풀무원식품,풀무원 공식몰,44443,생만두 갓김치 (400g),81,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출이미지\n여수 돌산갓 100%\n생만두 ...,NaN,배송정보\n일반배송\n새벽배송
1,풀무원,풀무원식품,풀무원 공식몰,43087,생만두 새우청경채 (320g),725,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n탱글한 새우의 고소함! 신선한...,NaN,배송정보\n일반배송\n새벽배송
2,풀무원,풀무원식품,풀무원 공식몰,43085,생만두 고기미나리 (400g),694,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n채즙까지 살렸다! 산뜻한 미나...,NaN,배송정보\n일반배송\n새벽배송
3,풀무원,풀무원지구식단,풀무원 공식몰,40337,[풀무원지구식단]이슬만두 부추새송이 (1.02kg),1747,12980,9980,23,"상품정보 영역\nbi_pulmuone\n연출 이미지\n밀가루 0%, 글루텐프리 식물...",NaN,배송정보\n일반배송\n새벽배송
4,풀무원,풀무원식품,풀무원 공식몰,1256,육즙 듬뿍 만두 (간편트레이) (150g),679,4000,2980,25,상품정보 영역\nbi_pulmuone\n연출 이미지\n풍부한 육즙 듬뿍 만두\n육즙...,NaN,배송정보\n일반배송\n새벽배송

In [ ]:
# 풀무원 순위 열 생성 + 열 이름 변경
풀무원메타['순위'] = range(1, len(풀무원메타) + 1)
풀무원메타 = 풀무원메타.rename(columns={'배송종류': '배송'})
풀무원메타 = 풀무원메타.rename(columns={'리뷰수': '리뷰 수'})
풀무원메타 = 풀무원메타.rename(columns={'만두 상세내용': '만두상세내용'})
풀무원메타.head(5)

,브랜드1,브랜드2,판매처,상품ID,상품명,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송,순위
0,풀무원,풀무원식품,풀무원 공식몰,44443,생만두 갓김치 (400g),81,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출이미지\n여수 돌산갓 100%\n생만두 ...,NaN,배송정보\n일반배송\n새벽배송,1
1,풀무원,풀무원식품,풀무원 공식몰,43087,생만두 새우청경채 (320g),725,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n탱글한 새우의 고소함! 신선한...,NaN,배송정보\n일반배송\n새벽배송,2
2,풀무원,풀무원식품,풀무원 공식몰,43085,생만두 고기미나리 (400g),694,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n채즙까지 살렸다! 산뜻한 미나...,NaN,배송정보\n일반배송\n새벽배송,3
3,풀무원,풀무원지구식단,풀무원 공식몰,40337,[풀무원지구식단]이슬만두 부추새송이 (1.02kg),1747,12980,9980,23,"상품정보 영역\nbi_pulmuone\n연출 이미지\n밀가루 0%, 글루텐프리 식물...",NaN,배송정보\n일반배송\n새벽배송,4
4,풀무원,풀무원식품,풀무원 공식몰,1256,육즙 듬뿍 만두 (간편트레이) (150g),679,4000,2980,25,상품정보 영역\nbi_pulmuone\n연출 이미지\n풍부한 육즙 듬뿍 만두\n육즙...,NaN,배송정보\n일반배송\n새벽배송,5

In [ ]:
# 풀무원 '평균 별점' 열 새로 생성 후 결측값 넣기
풀무원메타['평균 별점'] = None
풀무원메타.head(5)

,브랜드1,브랜드2,판매처,상품ID,상품명,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송,순위,평균 별점
0,풀무원,풀무원식품,풀무원 공식몰,44443,생만두 갓김치 (400g),81,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출이미지\n여수 돌산갓 100%\n생만두 ...,NaN,배송정보\n일반배송\n새벽배송,1,None
1,풀무원,풀무원식품,풀무원 공식몰,43087,생만두 새우청경채 (320g),725,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n탱글한 새우의 고소함! 신선한...,NaN,배송정보\n일반배송\n새벽배송,2,None
2,풀무원,풀무원식품,풀무원 공식몰,43085,생만두 고기미나리 (400g),694,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n채즙까지 살렸다! 산뜻한 미나...,NaN,배송정보\n일반배송\n새벽배송,3,None
3,풀무원,풀무원지구식단,풀무원 공식몰,40337,[풀무원지구식단]이슬만두 부추새송이 (1.02kg),1747,12980,9980,23,"상품정보 영역\nbi_pulmuone\n연출 이미지\n밀가루 0%, 글루텐프리 식물...",NaN,배송정보\n일반배송\n새벽배송,4,None
4,풀무원,풀무원식품,풀무원 공식몰,1256,육즙 듬뿍 만두 (간편트레이) (150g),679,4000,2980,25,상품정보 영역\nbi_pulmuone\n연출 이미지\n풍부한 육즙 듬뿍 만두\n육즙...,NaN,배송정보\n일반배송\n새벽배송,5,None

In [ ]:
풀무원메타.columns

Index(['브랜드1', '브랜드2', '판매처', '상품ID', '상품명', '리뷰 수', '정가', '할인가', '할인율',
       '만두상세내용', '대체지표', '배송', '순위', '평균 별점'],
      dtype='object')

In [ ]:
풀무원메타 = 풀무원메타[
    ['브랜드1', '브랜드2', '판매처', '순위', '상품ID', '상품명',
     '평균 별점', '리뷰 수', '정가', '할인가', '할인율',
     '만두상세내용', '대체지표', '배송']
]

풀무원메타.head()

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
0,풀무원,풀무원식품,풀무원 공식몰,1,44443,생만두 갓김치 (400g),None,81,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출이미지\n여수 돌산갓 100%\n생만두 ...,NaN,배송정보\n일반배송\n새벽배송
1,풀무원,풀무원식품,풀무원 공식몰,2,43087,생만두 새우청경채 (320g),None,725,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n탱글한 새우의 고소함! 신선한...,NaN,배송정보\n일반배송\n새벽배송
2,풀무원,풀무원식품,풀무원 공식몰,3,43085,생만두 고기미나리 (400g),None,694,6980,4980,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n채즙까지 살렸다! 산뜻한 미나...,NaN,배송정보\n일반배송\n새벽배송
3,풀무원,풀무원지구식단,풀무원 공식몰,4,40337,[풀무원지구식단]이슬만두 부추새송이 (1.02kg),None,1747,12980,9980,23,"상품정보 영역\nbi_pulmuone\n연출 이미지\n밀가루 0%, 글루텐프리 식물...",NaN,배송정보\n일반배송\n새벽배송
4,풀무원,풀무원식품,풀무원 공식몰,5,1256,육즙 듬뿍 만두 (간편트레이) (150g),None,679,4000,2980,25,상품정보 영역\nbi_pulmuone\n연출 이미지\n풍부한 육즙 듬뿍 만두\n육즙...,NaN,배송정보\n일반배송\n새벽배송

In [ ]:
비비고메타 = own_bibi_meta.copy()
비비고메타.head(1)

,브랜드1,브랜드2,판매처,상품ID,상품명,리뷰평점,리뷰수,정가,할인가,할인율,만두 상세내용,대체지표1,배송종류,Unnamed: 13,상세URL
0,비비고,NaN,CJ더마켓,40207361,비비고 왕교자 1.05kg,4.9,3229,10980.0,9991,9%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3...",NaN,https://www.cjthemarket.com/pc/prod/prodDetail...

In [ ]:
비비고메타['순위'] = range(1, len(비비고메타) + 1)
# 비비고메타 리뷰 평점 열 삭제
비비고메타 = 비비고메타.drop(columns=['Unnamed: 13', '상세URL'])
비비고메타.head(1)

,브랜드1,브랜드2,판매처,상품ID,상품명,리뷰평점,리뷰수,정가,할인가,할인율,만두 상세내용,대체지표1,배송종류,순위
0,비비고,NaN,CJ더마켓,40207361,비비고 왕교자 1.05kg,4.9,3229,10980.0,9991,9%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3...",1

In [ ]:
# 열 이름 수정
비비고메타 = 비비고메타.rename(columns={'대체지표1': '대체지표'})
비비고메타 = 비비고메타.rename(columns={'배송종류': '배송'})
비비고메타 = 비비고메타.rename(columns={'리뷰평점': '평균 별점'})
비비고메타 = 비비고메타.rename(columns={'리뷰수': '리뷰 수'})
비비고메타 = 비비고메타.rename(columns={'만두 상세내용': '만두상세내용'})
비비고메타.head(1)

,브랜드1,브랜드2,판매처,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송,순위
0,비비고,NaN,CJ더마켓,40207361,비비고 왕교자 1.05kg,4.9,3229,10980.0,9991,9%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3...",1

In [ ]:
비비고메타.columns

Index(['브랜드1', '브랜드2', '판매처', '상품ID', '상품명', '평균 별점', '리뷰 수', '정가', '할인가',
       '할인율', '만두상세내용', '대체지표', '배송', '순위'],
      dtype='object')

In [ ]:
비비고메타 = 비비고메타[
    ['브랜드1', '브랜드2', '판매처', '순위', '상품ID', '상품명',
     '평균 별점', '리뷰 수', '정가', '할인가', '할인율',
     '만두상세내용', '대체지표', '배송']
]

비비고메타.head()

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
0,비비고,NaN,CJ더마켓,1,40207361,비비고 왕교자 1.05kg,4.9,3229,10980.0,9991,9%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3..."
1,비비고,NaN,CJ더마켓,2,40207432,비비고 김치왕교자 1.05kg,4.8,1347,12480.0,10732,14%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3..."
2,비비고,NaN,CJ더마켓,3,40217533,[첫구매전용]비비고 왕교자 1.05kgX2개,4.9,3229,NaN,21960,NaN,"APP전용 70% 할인 받으면 ✨6,588원✨",NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3..."
3,비비고,NaN,CJ더마켓,4,40218310,[더마켓 ONLY]얇은피 왕교자 1.05kg,4.8,1715,10980.0,9442,14%,NaN,NaN,"내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동 배송비 3,000원 (3..."
4,비비고,NaN,CJ더마켓,5,40223080,[만두세트]비비고 왕교자1.05kgX3개+315g 총 4개,4.9,59,39520.0,28849,27%,NaN,NaN,내일 3/14(토) 도착예정 오네배송예정일 상세 보기 냉동무료배송 무료배송 기준 상...

In [ ]:
오뚜기메타 = own_oto_meta.copy()
오뚜기메타.head(5)

,브랜드,브랜드라인,상품ID,상품명,별점,리뷰수,정가,할인가,배송비,카테고리,상품_url
0,오뚜기,X.O.,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,3000,만두,https://www.otokimall.com/front/product/846
1,오뚜기,가뿐한끼,4381,가뿐한끼 닭가슴살 만두 오리지널 180G,5.0,27,30000,3480,3000,만두,https://www.otokimall.com/front/product/4381
2,오뚜기,가뿐한끼,4382,가뿐한끼 닭가슴살 만두 김치 180G,4.8,32,30000,3480,3000,만두,https://www.otokimall.com/front/product/4382
3,오뚜기,X.O.,845,X.O. 교자 (324GX2),4.9,35,30000,10480,3000,만두,https://www.otokimall.com/front/product/845
4,오뚜기,X.O.,850,X.O. 교자김치 (360GX2),4.9,25,30000,10480,3000,만두,https://www.otokimall.com/front/product/850

In [ ]:
# 열 이름 수정
오뚜기메타 = 오뚜기메타.rename(columns={'브랜드': '브랜드1'})
오뚜기메타 = 오뚜기메타.rename(columns={'브랜드라인': '브랜드2'})
오뚜기메타 = 오뚜기메타.rename(columns={'별점': '평균 별점'})
오뚜기메타 = 오뚜기메타.rename(columns={'리뷰수': '리뷰 수'})
오뚜기메타 = 오뚜기메타.rename(columns={'배송비': '배송'})
오뚜기메타.head(1)

,브랜드1,브랜드2,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,배송,카테고리,상품_url
0,오뚜기,X.O.,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,3000,만두,https://www.otokimall.com/front/product/846

In [ ]:
# 비비고메타 리뷰 평점 열 삭제
오뚜기메타 = 오뚜기메타.drop(columns=['카테고리', '상품_url'])

# 순위 열 생성
오뚜기메타['순위'] = range(1, len(오뚜기메타) + 1)
오뚜기메타.head(1)

,브랜드1,브랜드2,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,배송,순위
0,오뚜기,X.O.,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,3000,1

In [ ]:
오뚜기메타['판매처'] = '오뚜기자사몰'
오뚜기메타.head(1)

,브랜드1,브랜드2,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,배송,순위,판매처
0,오뚜기,X.O.,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,3000,1,오뚜기자사몰

In [ ]:
# 할인율 열 생성 + 값 추가 (할인율 = (정가 - 할인가) / 정가 * 100). 뒤에 소수점 첫째 자리에서 반올림. 소수점 안 나오게 하기
오뚜기메타['할인율'] = (((오뚜기메타['정가'] - 오뚜기메타['할인가']) / 오뚜기메타['정가']) * 100).round().astype(int)
오뚜기메타.head(1)

,브랜드1,브랜드2,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,배송,순위,판매처,할인율
0,오뚜기,X.O.,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,3000,1,오뚜기자사몰,65

In [ ]:
오뚜기메타['만두상세내용'] = None
오뚜기메타['대체지표'] = None

In [ ]:
오뚜기메타.columns

Index([            '브랜드1',             '브랜드2',             '상품ID',
                    '상품명',            '평균 별점',             '리뷰 수',
                     '정가',              '할인가',               '배송',
                     '순위',              '판매처',              '할인율',
       ('만두상세내용', '대체지표'),           '만두상세내용',             '대체지표'],
      dtype='object')

In [ ]:
오뚜기메타 = 오뚜기메타[
    ['브랜드1', '브랜드2', '판매처', '순위', '상품ID', '상품명',
     '평균 별점', '리뷰 수', '정가', '할인가', '할인율',
     '만두상세내용', '대체지표', '배송']
]

오뚜기메타.head()

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
0,오뚜기,X.O.,오뚜기자사몰,1,846,X.O. 교자새우&홍게살 (324GX2),4.9,74,30000,10480,65,None,None,3000
1,오뚜기,가뿐한끼,오뚜기자사몰,2,4381,가뿐한끼 닭가슴살 만두 오리지널 180G,5.0,27,30000,3480,88,None,None,3000
2,오뚜기,가뿐한끼,오뚜기자사몰,3,4382,가뿐한끼 닭가슴살 만두 김치 180G,4.8,32,30000,3480,88,None,None,3000
3,오뚜기,X.O.,오뚜기자사몰,4,845,X.O. 교자 (324GX2),4.9,35,30000,10480,65,None,None,3000
4,오뚜기,X.O.,오뚜기자사몰,5,850,X.O. 교자김치 (360GX2),4.9,25,30000,10480,65,None,None,3000

In [ ]:
네이버메타 = pd.read_csv('메타데이터_네이버.csv')
쿠팡메타 = pd.read_csv('메타데이터_쿠팡.csv')

In [ ]:
# 네이버메타 브랜드2 열에 판매처 열의 값 복사
네이버메타['브랜드2'] = 네이버메타['판매처']

# 네이버메타 판매처에 '네이버'입력
네이버메타['판매처'] = '네이버'
네이버메타.head(1)

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
0,비비고,CJ제일제당,네이버,1,6.372126e+09,"비비고 왕교자 455g, 6개",4.86,50026.0,29940.0,26940,10%,교자,NaN,무료배송

In [ ]:
# 네이버메타 브랜드2의 모든 행 출력
네이버메타['브랜드2']

0            CJ제일제당
1            CJ제일제당
2            CJ제일제당
3            CJ제일제당
4            CJ제일제당
           ...
394          한스 프레쉬
395        이마트에브리데이
396          그린푸드마켓
397             식재온
398    MONDAY NIGHT
Name: 브랜드2, Length: 399, dtype: object

In [ ]:
# 풀무원메타, 비비고메타, 오뚜기메타, 네이버메타, 쿠팡메타 병합. 이름은 'total_meta'로. 브랜드1, 브랜드2, 판매처, 순위, 상품ID, 상품명, 평균 별점, 리뷰 수, 정가, 할인가, 할인율, 만두상세내용, 대체지표, 배송 열로 구성
total_meta = pd.concat([풀무원메타, 비비고메타, 오뚜기메타, 네이버메타, 쿠팡메타], ignore_index=True)
total_meta.head()

C:\Users\user\AppData\Local\Temp\ipykernel_10128\2540695445.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  total_meta = pd.concat([풀무원메타, 비비고메타, 오뚜기메타, 네이버메타, 쿠팡메타], ignore_index=True)

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
0,풀무원,풀무원식품,풀무원 공식몰,1,44443,생만두 갓김치 (400g),NaN,81.0,6980.0,4980.0,28,상품정보 영역\nbi_pulmuone\n연출이미지\n여수 돌산갓 100%\n생만두 ...,NaN,배송정보\n일반배송\n새벽배송
1,풀무원,풀무원식품,풀무원 공식몰,2,43087,생만두 새우청경채 (320g),NaN,725.0,6980.0,4980.0,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n탱글한 새우의 고소함! 신선한...,NaN,배송정보\n일반배송\n새벽배송
2,풀무원,풀무원식품,풀무원 공식몰,3,43085,생만두 고기미나리 (400g),NaN,694.0,6980.0,4980.0,28,상품정보 영역\nbi_pulmuone\n연출 이미지\n채즙까지 살렸다! 산뜻한 미나...,NaN,배송정보\n일반배송\n새벽배송
3,풀무원,풀무원지구식단,풀무원 공식몰,4,40337,[풀무원지구식단]이슬만두 부추새송이 (1.02kg),NaN,1747.0,12980.0,9980.0,23,"상품정보 영역\nbi_pulmuone\n연출 이미지\n밀가루 0%, 글루텐프리 식물...",NaN,배송정보\n일반배송\n새벽배송
4,풀무원,풀무원식품,풀무원 공식몰,5,1256,육즙 듬뿍 만두 (간편트레이) (150g),NaN,679.0,4000.0,2980.0,25,상품정보 영역\nbi_pulmuone\n연출 이미지\n풍부한 육즙 듬뿍 만두\n육즙...,NaN,배송정보\n일반배송\n새벽배송

In [ ]:
# total_meta 저장
total_meta.to_csv('total_meta.csv', index=False)

In [ ]:
total_meta[total_meta['판매처'] == '네이버']

,브랜드1,브랜드2,판매처,순위,상품ID,상품명,평균 별점,리뷰 수,정가,할인가,할인율,만두상세내용,대체지표,배송
211,비비고,CJ제일제당,네이버,1,6372125746.0,"비비고 왕교자 455g, 6개",4.86,50026.0,29940.0,26940.0,10%,교자,NaN,무료배송
212,비비고,CJ제일제당,네이버,2,7999622600.0,"비비고 만두세트 10봉(왕교자3,김치왕교자3,청양고기2,진한김치2)",4.87,39493.0,69200.0,30900.0,55%,"교자, 김치왕교자",NaN,무료배송
213,비비고,CJ제일제당,네이버,3,9678039523.0,"비비고 김치왕교자 1.05kg, 4개",4.80,3635.0,47920.0,38900.0,18%,"교자, 김치왕교자",NaN,무료배송
214,비비고,CJ제일제당,네이버,4,6942415780.0,비비고 왕교자 1.05KGx2개+김치 왕교자 420Gx2개,4.86,1159.0,31940.0,26560.0,16%,교자,NaN,무료배송
215,비비고,CJ제일제당,네이버,5,6063362669.0,"비비고 든든한섬만두 384g, 6개",4.87,197.0,29940.0,26940.0,10%,만두,NaN,무료배송
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,풀무원,한스 프레쉬,네이버,146,9576335705.0,풀무원 부추잡채 지짐만두 300g x 3봉,4.67,12.0,NaN,10980.0,NaN,만두,NaN,NaN
606,풀무원,이마트에브리데이,네이버,147,NaN,풀무원 얇은피 꽉찬속 고기만두 400g x 2,4.81,103.0,NaN,8980.0,NaN,고기만두,NaN,NaN
607,풀무원,그린푸드마켓,네이버,148,11924092768.0,풀무원 풀스키친 얇은피 김치만두 1.2kg,5.00,3.0,NaN,12600.0,NaN,김치만두,NaN,NaN
608,풀무원,식재온,네이버,149,11179610189.0,김치메밀전병 냉동 500g,5.00,1.0,11500.0,8500.0,26%,만두,NaN,NaN
609,풀무원,MONDAY NIGHT,네이버,150,8931738246.0,풀무원 손만두 풀스키친 속이 꽉찬 (냉동) 1개 1.4kg,5.00,1.0,17810.0,15220.0,14%,만두,NaN,NaN